---
deployment:
  tasks:
    - export DEPLOYPATH=/home/macinnovafrica/public_html/
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - npm install
    - npm run build